# General example for adding mounts to CAS workers
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: data-mounts-cas
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/volumes/-
    value:
      name: data-access
      persistentVolumeClaim:
        claimName: sas-access-clients
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/volumeMounts/-
    value:
      name: data-access
      mountPath: "/access-clients"
target:
  kind: CASDeployment
  annotationSelector: sas.com/sas-access-config=true
