# General example for adding mounts to SAS containers with a
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: data-mounts-job
patch: |-
  - op: add
    path: /template/spec/volumes/-
    value:
      name: data-access
      persistentVolumeClaim:
        claimName: sas-access-clients
  - op: add
    path: /template/spec/containers/0/volumeMounts/-
    value:
      name: data-access
      mountPath: "/access-clients"
target:
  kind: PodTemplate
  annotationSelector: sas.com/sas-access-config=true