# General example for adding mounts to SAS containers with a
# PatchTransformer
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: data-mounts-statefulset
patch: |-
  ## NFS path example - kubernetes will mount these for you
  - op: add
    path: /spec/template/spec/volumes/-
    value:
      name: data-access
      persistentVolumeClaim:
        claimName: sas-access-clients
  - op: add
    path: /spec/template/spec/containers/0/volumeMounts/-
    value:
      name: data-access
      mountPath: "/access-clients"
target:
  kind: StatefulSet
  group: apps
  annotationSelector: sas.com/sas-access-config=true