apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-access-clients
  namespace: sas-viya
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-sasviyadev-sc