apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-sasdata
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources: 
    requests:
      storage: 200Gi
  storageClassName: nfs-sasviyadev-sc